import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// import { Providers } from "@/providers/Providers";
import { ThemeProvider } from "@/components/theme-provider";
import Navbar from "@/components/Navbar";
// import { SessionProvider } from "next-auth/react";
import Sessionprovider from "@/providers/SessionProvider";
import { Toaster } from "@/components/ui/toaster";
import { Providers } from "@/providers/AuthProvider";


const inter = Inter({ subsets: ["latin"], variable: "--font-inter"  });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
     <body
  className={`antialiased bg-[linear-gradient(135deg,_#1e1e1e,_#0a0a0a,_#141414)] bg-[length:150%_150%] animate-[galaxyPulse_8s_ease-in-out_infinite]`}
  style={{ color: 'white' }}
>

        <Providers>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
          <main className="max-w-7xl mx-auto p-10 space-y-10">
          <Navbar/>
          {children}
          </main>
          <Toaster/>
          </ThemeProvider>
        <Sessionprovider/>
        </Providers>
        </body>
    </html>
  );
}
