import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { ThemeProvider } from "@/providers/theme-provider";


import Sessionprovider from "@/providers/SessionProvider";
import { Toaster } from "@/components/ui/toaster";
import { Providers } from "@/providers/AuthProvider";
import Navbar from "@/components/layouts/Navbar";


const inter = Inter({ subsets: ["latin"], variable: "--font-inter"  });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body
  className={`${inter.variable} antialiased bg-[linear-gradient(145deg,_#000000,_#1b1b1b,_#3d3d3d,_#101010)] bg-[length:200%_200%] animate-[neonGlow_5s_ease-in-out_infinite]`}
  style={{ color: 'white' }}
>


        <Providers>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
          <main className="max-w-7xl mx-auto p-10 space-y-10">
          <Navbar />
          {children}
          </main>
          <Toaster/>
          </ThemeProvider>
        <Sessionprovider/>
        </Providers>
        </body>
    </html>
  );
}
